<?php

namespace ContainerYbx6uIN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllereditUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gyqkGSs.App\Controller\AdminController::editUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gyqkGSs.App\\Controller\\AdminController::editUser()'] = ($container->privates['.service_locator.gyqkGSs'] ?? $container->load('get_ServiceLocator_GyqkGSsService'))->withContext('App\\Controller\\AdminController::editUser()', $container);
    }
}
