<?php

namespace ContainerYbx6uIN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthControllerpatchSaveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4eE5_7S.App\Controller\Api\AuthController::patchSave()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4eE5_7S.App\\Controller\\Api\\AuthController::patchSave()'] = ($container->privates['.service_locator.4eE5_7S'] ?? $container->load('get_ServiceLocator_4eE57SService'))->withContext('App\\Controller\\Api\\AuthController::patchSave()', $container);
    }
}
