<?php

namespace ContainerYbx6uIN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthControllerloginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7xU5P93.App\Controller\Api\AuthController::login()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7xU5P93.App\\Controller\\Api\\AuthController::login()'] = ($container->privates['.service_locator.7xU5P93'] ?? $container->load('get_ServiceLocator_7xU5P93Service'))->withContext('App\\Controller\\Api\\AuthController::login()', $container);
    }
}
