<?php

namespace ContainerGDgx3xm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerloginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p66hxK8.App\Controller\AdminController::login()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p66hxK8.App\\Controller\\AdminController::login()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'passwordHasher' => '?',
        ]))->withContext('App\\Controller\\AdminController::login()', $container);
    }
}
