<?php

namespace ContainerCzZ25CY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_28epnQUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.28epnQU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.28epnQU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AdminController::dashboard' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\AdminController::dashboard()', 'getAdminControllerdashboardService', true],
            'App\\Controller\\AdminController::login' => ['privates', '.service_locator.p66hxK8.App\\Controller\\AdminController::login()', 'getAdminControllerloginService', true],
            'App\\Controller\\AdminController::createUser' => ['privates', '.service_locator.gyqkGSs.App\\Controller\\AdminController::createUser()', 'getAdminControllercreateUserService', true],
            'App\\Controller\\AdminController::editUser' => ['privates', '.service_locator.gyqkGSs.App\\Controller\\AdminController::editUser()', 'getAdminControllereditUserService', true],
            'App\\Controller\\AdminController::deleteUser' => ['privates', '.service_locator.4eE5_7S.App\\Controller\\AdminController::deleteUser()', 'getAdminControllerdeleteUserService', true],
            'App\\Controller\\AdminController::showUser' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\AdminController::showUser()', 'getAdminControllershowUserService', true],
            'App\\Controller\\Api\\AuthController::register' => ['privates', '.service_locator.7xU5P93.App\\Controller\\Api\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\Api\\AuthController::login' => ['privates', '.service_locator.7xU5P93.App\\Controller\\Api\\AuthController::login()', 'getAuthControllerloginService', true],
            'App\\Controller\\Api\\AuthController::me' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\Api\\AuthController::me()', 'getAuthControllermeService', true],
            'App\\Controller\\Api\\AuthController::save' => ['privates', '.service_locator.4eE5_7S.App\\Controller\\Api\\AuthController::save()', 'getAuthControllersaveService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AdminController:dashboard' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\AdminController::dashboard()', 'getAdminControllerdashboardService', true],
            'App\\Controller\\AdminController:login' => ['privates', '.service_locator.p66hxK8.App\\Controller\\AdminController::login()', 'getAdminControllerloginService', true],
            'App\\Controller\\AdminController:createUser' => ['privates', '.service_locator.gyqkGSs.App\\Controller\\AdminController::createUser()', 'getAdminControllercreateUserService', true],
            'App\\Controller\\AdminController:editUser' => ['privates', '.service_locator.gyqkGSs.App\\Controller\\AdminController::editUser()', 'getAdminControllereditUserService', true],
            'App\\Controller\\AdminController:deleteUser' => ['privates', '.service_locator.4eE5_7S.App\\Controller\\AdminController::deleteUser()', 'getAdminControllerdeleteUserService', true],
            'App\\Controller\\AdminController:showUser' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\AdminController::showUser()', 'getAdminControllershowUserService', true],
            'App\\Controller\\Api\\AuthController:register' => ['privates', '.service_locator.7xU5P93.App\\Controller\\Api\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\Api\\AuthController:login' => ['privates', '.service_locator.7xU5P93.App\\Controller\\Api\\AuthController::login()', 'getAuthControllerloginService', true],
            'App\\Controller\\Api\\AuthController:me' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\Api\\AuthController::me()', 'getAuthControllermeService', true],
            'App\\Controller\\Api\\AuthController:save' => ['privates', '.service_locator.4eE5_7S.App\\Controller\\Api\\AuthController::save()', 'getAuthControllersaveService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminController::dashboard' => '?',
            'App\\Controller\\AdminController::login' => '?',
            'App\\Controller\\AdminController::createUser' => '?',
            'App\\Controller\\AdminController::editUser' => '?',
            'App\\Controller\\AdminController::deleteUser' => '?',
            'App\\Controller\\AdminController::showUser' => '?',
            'App\\Controller\\Api\\AuthController::register' => '?',
            'App\\Controller\\Api\\AuthController::login' => '?',
            'App\\Controller\\Api\\AuthController::me' => '?',
            'App\\Controller\\Api\\AuthController::save' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminController:dashboard' => '?',
            'App\\Controller\\AdminController:login' => '?',
            'App\\Controller\\AdminController:createUser' => '?',
            'App\\Controller\\AdminController:editUser' => '?',
            'App\\Controller\\AdminController:deleteUser' => '?',
            'App\\Controller\\AdminController:showUser' => '?',
            'App\\Controller\\Api\\AuthController:register' => '?',
            'App\\Controller\\Api\\AuthController:login' => '?',
            'App\\Controller\\Api\\AuthController:me' => '?',
            'App\\Controller\\Api\\AuthController:save' => '?',
        ]);
    }
}
