<?php

namespace ContainerCzZ25CY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7xU5P93.App\Controller\Api\AuthController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7xU5P93.App\\Controller\\Api\\AuthController::register()'] = ($container->privates['.service_locator.7xU5P93'] ?? $container->load('get_ServiceLocator_7xU5P93Service'))->withContext('App\\Controller\\Api\\AuthController::register()', $container);
    }
}
